#!/usr/bin/env bash
# Copy the url of the active ngrok connection to the clipboard.  Updated for latest ngrok (Oct 2019)
#
# Usage:
#   ngrok-copy     # copies e.g. https://3cd67858.ngrok.io to clipboard.
#   ngrok-copy -u  # copies e.g. http://3cd67858.ngrok.io to clipboard.
#
# Modified from the original script at https://gist.github.com/mlsteele/f57adc1fab5c44656d6d


if [[ "$1" == "-u" ]]; then
    NGROK_URL=`curl -s http://127.0.0.1:4040/api/tunnels | grep "http://\w*.ngrok.io"  -oh`
else
    NGROK_URL=`curl -s http://127.0.0.1:4040/api/tunnels | grep "https://\w*.ngrok.io"  -oh`
fi

if [[ $NGROK_URL != *"http"* ]]; then
    echo "No url found. Is ngrok running?"
    exit 1
fi

if [ "$(uname)" == "Darwin" ]; then
    # OSX
    echo $NGROK_URL | pbcopy
else
    # Linux
    echo $NGROK_URL | xclip -selection clipboard
fi
echo "Copied to clipboard: $NGROK_URL"